### ISSUE TITLE
Error updating WhatsApp Web

### ISSUE THREAD

**Issue by nplezka** [alindt/WhatsUpp#13]
### System details

* OS: Ubuntu 19.04
* App Version: 0.6.1
* Desktop Environment: GNOME 3.22

### Expected behaviour

Just update WhatsApp Web.

### Actual behaviour

![image](https://user-images.githubusercontent.com/10550382/57371633-8959b680-7193-11e9-8160-030642138b78.png)

### Step to reproduce the behaviour

Click on "Update WhatsApp" in the main page.

**Comment by alindt** [comment]
@nplezka, please test the latest dev-release (https://github.com/alindt/WhatsUpp/releases/tag/dev-2019050903-gita32ce21) and see if the issue is still present.
